### ISSUE TITLE
Please Update .gitignore

### ISSUE THREAD

**Issue by tcwan** [mindboards/ev3sources#11]
Please add '.DS_Store' to the .gitignore file. 
This is generated by Mac OS X.

**Comment by sheabunge** [comment]
We can add this to the file, but you might also want to create a [global .gitignore](https://help.github.com/articles/ignoring-files#global-gitignore) and add `.DS_Store` to that.

**Comment by tcwan** [comment]
Thanks. Your solution is better. I didn't know that I can create a global .gitignore file...
