### ISSUE TITLE
Proposed Update to README.md

### ISSUE THREAD

**Issue by tcwan** [mindboards/ev3sources#12]
I'm proposing updating the README.md file with the following paragraph after Item No. 1. This is posted here since I haven't forked the repository and don't want to commit it before getting consensus on this.
## Things you will need
- A Linux (virtual) installation.  I used Ubuntu 13.04 on VMware Workstation, but I am sure other combinations also work.
  
  The reason for the Linux installation requirement is due to the case-sensitive filenames used by the Linux kernel source repository. Attempting to clone the source repository to a non-case sensitive file system such as Mac OSX HFS+ or Windows FAT would result in a corrupted repository.
- Eclipse.  I used Helios Service Release 1, but I know more recent versions will also work.

...

**Comment by sheabunge** [comment]
Perhaps this information could be moved to a wiki page so that anyone can contribute to it, even if they have not forked the repo or use Git?

**Comment by tcwan** [comment]
That is fine, except that this particular issue is something that should be clearly understood by people who're keen on getting started. Since the README.md file exists already I just thought it would be easiest to put it there.

**Comment by sheabunge** [comment]
Very well. I will add this information to README.md. I know that Xander was hoping to eventually wikify all of this content eventually, but I guess it can stay in the readme for now.
