### ISSUE TITLE
I am on vacation

### ISSUE THREAD

**Issue by botbench** [mindboards/ev3sources#14]
Peeps,

I am on vacation at the moment and am not able to go through all these issues and pull requests.  @bungeshea , could you look at them and merge them if they're good?

**Comment by sheabunge** [comment]
I can help out with issues regarding maintaining the repository, but I don't really know a lot about the actual source code. I guess can review the open pull requests and merge them if you like.

**Comment by botbench** [comment]
I don't think many of the requests are code related,  are they? I think most are build system related. I can take a look at them tomorrow, if that would make you more comfortable. Today is a bit hectic,  but I should have more time tomorrow. Typos are courtesy of my phone. :-)
