### ISSUE TITLE
Source repository includes many generated files

### ISSUE THREAD

**Issue by schodet** [mindboards/ev3sources#2]
This includes .o, .d, .cmd, doxygen doc, etc.

**Comment by botbench** [comment]
Yeah, I pushed the tree in a bit of a hurry and had run a build just before I pushed it to ensure it was working :)
I will clean it up and do another push.

**Comment by schodet** [comment]
OK, thanks.

**Comment by botbench** [comment]
This should be fixed now.

**Comment by schodet** [comment]
There are still plenty generated files, I am preparing a pull request for linux kernel.

**Comment by botbench** [comment]
Sounds good!  Thanks :+1:
