### ISSUE TITLE
Is it possible to reverse engineer wifi and bluetooth protocols from the source code?

### ISSUE THREAD

**Issue by wenchaojiang** [mindboards/ev3sources#21]
I am web programmer with no knowledge in embedded system. 

I quite interested in knowing network protocols of ev3 so that I can write customised program to control my robots remotely. Searching docs for two days,  I can not find any docs. If you know any existing docs plz plz let me know. If there isn't, any possibility to reverse engineer it from the source tree?

**Comment by botbench** [comment]
You should take a look here: http://www.monobrick.dk/guides/how-to-establish-a-wifi-connection-with-the-ev3-brick/

There are currently no docs about this stuff :(

**Comment by dlech** [comment]
Actually, there is. If you clone the ev3sources repo and run `make doc.view`, it will open the docs in a web browser. Follow the link that says "Communication"

**Comment by botbench** [comment]
I am not sure that list is exhaustive.  They provide a list of examples :)

**Comment by thiagomarzagao** [comment]
I've went through the docs and examples and they helped a lot - I'm finally able to start and stop motors using C++, via Bluetooth.

Now, I can't seem to figure out how to retrieve data from the sensors. I'm guessing this is probably the wrong place to ask, but could anyone take a look at my code snippet and tell me what I'm doing wrong? It's here: http://stackoverflow.com/questions/24253509/using-c-to-get-data-from-a-lego-ev3-sensor
