### ISSUE TITLE
Can not format SD card

### ISSUE THREAD

**Issue by 1plus4** [mindboards/ev3sources#26]
In format_sdcard.sh file, when fdisk command is run(70th line of format_sdcard.sh), fdisk.cmd file is passed as argument.
In fdisk.cmd file, it seems that initial sector is configured 1(10th line of fdisk.cmd), but initial sector is not always 1(for example, default: 2048).
Perhaps you shoud modify line feed in 10th line of fdisk.cmd to configure default parameter.

**Comment by botbench** [comment]
This should be fixed in your commit :)
