### ISSUE TITLE
Encourage people to use forks instead of branches?

### ISSUE THREAD

**Issue by sheabunge** [mindboards/ev3sources#3]
I noticed that you've started encouraging people to use their own branches for personal modifications instead of the master branch. This is a great idea, but could me improved upon by encouraging the use of forks.

How forks work, is anyone can click on the Fork button at the top of the page, and it creates a copy of the repository under their own account. They can then modify things as they see fit. If they think that their changes should be pushed to the main repo, they can submit a pull request for discussion.

**Comment by botbench** [comment]
Yes, you are right, of course. This was more for people with commit access the master repo :)
