### ISSUE TITLE
Can not make modules in linux kernel

### ISSUE THREAD

**Issue by schodet** [mindboards/ev3sources#6]
It seems that ath drivers were backported from a more recent kernel. As a result, there are other wifi drivers which no longer compile. Those drivers are however enabled as module in the configuration.
What could be done? Find where the ath changes come from, and fix the backport.

**Comment by botbench** [comment]
This was something that one of the guys at the OHM2013 mentioned as well.  The issue is that this is all the source code we've been given.  If it doesn't work, I can try and get some answers from the main dev at LEGO and see what he says.

**Comment by searly** [comment]
I guess that is why the "make modules" and "make modules_install" lines are commented out in the build_kernel.sh script? It looks like the shipping ev3 firmware  contains only the custom kernel modules that are built as part of the lms2012 application. These show up at /home/root/lms2012/sys/mod/
/sys/mod is empty.

**Comment by schodet** [comment]
But /lib/modules/2.6.33-rc4 is not empty in the lmsfs.tar.bz2 file which is used as the file system root.

**Comment by searly** [comment]
Oh you're right. Still the modules installed there are not up to date with everything configured as a module in LEGOBoard.config. (eg. gadget ethernet driver is missing)

**Comment by perelloc** [comment]
Its wierd. lmsfs.tar.bz2 seems to be the filesystem that is writen to the SD card using update_card.sh. But there is no way to build it.

OTOH make_image.sh creates an up to date image but seems that its not used afterwards. 

I am misunderstanding something?

**Comment by schodet** [comment]
Yes, I suppose someone built lmsfs.tar.bz2 on its computer, but they did not feel the need to have full bundled source to regenerate it. It may have been assembled from existing ARM project.
I think that the image created with make_image.sh is only used for the internal flash.
