### ISSUE TITLE
Build script for firmware are fragile

### ISSUE THREAD

**Issue by botbench** [mindboards/ev3sources#8]
The build scripts found in lms2012/open_first are very fragile and have little or no error checking at any stage of the build process.
I propose we migrate them to an actual build system such as make or ant and use targets for each part that the build system is dependent on. 
The buildmod scripts found in each of the lms2012/d_\* folders are a good example of this as well.

**Comment by schodet** [comment]
I can help with this task if you want.

**Comment by botbench** [comment]
That would be great.
