### ISSUE TITLE
Problems at script build_kernel

### ISSUE THREAD

**Issue by pril** [mindboards/ev3sources#9]
I started to work with your ev3source. I'm working with an virtual Ubuntu environment and I try to compile the kernel, but unfortunately I've got an error. It seems to be an firmware library linkage within an compilling process. I'll append an picture of the build-script for the bug-research. May it's only a lack of understanding the right sequence of your scripts in the open-first-folder. I thank you for your cooperation and looking forward  to your responses to this issue.

It would be great, if you could
![bildschirmfoto 2013-08-08 um 16 42 09](https://f.cloud.github.com/assets/794141/932101/bca662bc-0039-11e3-8d9d-234c7d1f5e53.png)
 add an user-guit how to put the kernel on an EV3.

**Comment by botbench** [comment]
Do you have an English translation of the above error messages for those not familiar with the German language?  Also, were the steps you did to produce this error?

**Comment by pril** [comment]
Sorry, I should have considered that sooner. I'll assume that the Kernel-Modules are installed. 

Well, here are the steps to reproduce the given results:
1. Download and install the JRE
2. Download and install DaVinci-PSP-SDK-03.20.00.13
3. Create in your home-directory an folder "am1808" and put the Folder DaVinci-PSP-SDK-03.20.00.13 in it.
4. Install Code-Sourcery. It should be in a folder CodeSourcery at your home-Directory, too.
5. Ensure that everything is fine.
6. Clone the current source with the command git clone http://github.com/mindboards/ev3sources.git to your folder eve in your home-Directory.
7. Navigate through your Directories until you are in the Directory /home/<EV3-Source>/lms2012/open_first/.
7. Run the script env_setup.sh
8. Run the script build_kernel.sh
Then you'll receive the Messages from above. (in english)
![bildschirmfoto 2013-08-12 um 11 07 51](https://f.cloud.github.com/assets/794141/946353/bf8cf188-032e-11e3-8bb9-6a4355103f69.png)

**Comment by tcwan** [comment]
I haven't tried to build it yet, but the PRU files are for the AM1808-specific micro-RISC engine peripheral. You'll probably have to unzip the pru-firmware-05-31-2011-1423-v3.0.zip file, and tweak your paths to include pru-as found in

`pru-firmware-05-31-2011-1423-v3.0/pru/utils/pru-as/linux`

to build them.

**Comment by schodet** [comment]
The kernel sources are included in the git repository, you should use them as they were modified by LEGO. It should build almost out-of-the-box. Use the LEGOBoard.config from lms2012/open_first as .config file. It should be even easier when Makefiles will be pushed.

**Comment by botbench** [comment]
The kernel and modules now build cleanly with the latest merge.  Update your repo.
